apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brooks-ingress
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: mcrt-4c68d1bb-62e1-4830-a2ff-4aa8c8ae5ae3
    networking.gke.io/managed-certificates: brooks-managed-cert
spec:
  rules:
    - host: www.brooks-dusura.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brooks-app-service
                port:
                  number: 80
  tls:
    - hosts:
        - www.brooks-dusura.uk
      secretName: brooks-cert
