apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brooks-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Origin $http_origin;
      proxy_set_header Access-Control-Request-Method $http_access_control_request_method;
      proxy_set_header Access-Control-Request-Headers $http_access_control_request_headers;
spec:
  ingressClassName: nginx
  rules:
    - host: www.brooks-dusura.uk
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-server
                port:
                  number: 8080
          - path: /user-auth
            pathType: Prefix
            backend:
              service:
                name: authentication-server
                port:
                  number: 8081
          - path: /places
            pathType: Prefix
            backend:
              service:
                name: reflect-places-1
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brooks-app-service
                port:
                  number: 80
  tls:
    - hosts:
        - www.brooks-dusura.uk
      secretName: brooks-tls
