apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brooks-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    # CORS configurations
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://www.brooks-dusura.uk"
    nginx.ingress.kubernetes.io/proxy-method: "PATCH $request_method"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "off"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "off"

    # Add a configuration snippet to handle OPTIONS
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_method = OPTIONS) {
        add_header "Access-Control-Allow-Origin" "https://www.brooks-dusura.uk" always;
        add_header "Access-Control-Allow-Methods" "GET, POST, PUT, DELETE, OPTIONS" always;
        add_header "Access-Control-Allow-Headers" "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization" always;
        add_header "Access-Control-Max-Age" "86400" always;
        add_header "Content-Length" 0;
        add_header "Content-Type" "text/plain charset=UTF-8";
        return 204;
      }

spec:
  ingressClassName: nginx
  rules:
    - host: api.brooks-dusura.uk
      http:
        paths:
          - path: /user-auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: authentication-server
                port:
                  number: 8081
    - host: www.brooks-dusura.uk
      http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-server
                port:
                  number: 8080
          - path: /user-auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: authentication-server
                port:
                  number: 8081
          - path: /places(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: reflect-places-1
                port:
                  number: 8081
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: brooks-app-service
                port:
                  number: 80
  tls:
    - hosts:
        - www.brooks-dusura.uk
        - api.brooks-dusura.uk
      secretName: brooks-tls


#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: brooks-ingress
#  namespace: default
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: www.brooks-dusura.uk
#      http:
#        paths:
#          - path: /auth
#            pathType: Prefix
#            backend:
#              service:
#                name: auth-server
#                port:
#                  number: 8080
#          - path: /user-auth
#            pathType: Prefix
#            backend:
#              service:
#                name: authentication-server
#                port:
#                  number: 8081
#          - path: /places
#            pathType: Prefix
#            backend:
#              service:
#                name: reflect-places-1
#                port:
#                  number: 8081
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: brooks-app-service
#                port:
#                  number: 80
#  tls:
#    - hosts:
#        - www.brooks-dusura.uk
#      secretName: brooks-tls
