apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: debug-container
      image: ubuntu
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: postgres-storage
          mountPath: /mnt/postgres
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: postgres-pvc
