apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflect-places-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reflect-places-1
  template:
    metadata:
      labels:
        app: reflect-places-1
    spec:
      containers:
        - name: reflect-places-1
          # image: borissolomonia/reflect_places_1:latest #dockerhub ზე განთავსებული იმიჯია საჭირო
          image: IMAGE_URL
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_SERVER_ADDRESS
              value: "http://reflect-service-registry:8761/eureka"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              value: jdbc:postgresql://10.2.0.8:5432/postgres
            - name: AUTH_SERVER
              value: http://10.2.0.132:8080
            - name: AUTH_SERVER_JWKS
              value: http://10.2.0.132:8080/oauth2/jwks    
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: reflect-places-1
# spec:
#   ports:
#     - port: 8081
#       targetPort: 8081
#   selector:
#     app: reflect-places-1
apiVersion: v1
kind: Service
metadata:
  name: reflect-places-1
spec:
  type: LoadBalancer
  selector:
    app: reflect-places-1
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
